### PR TITLE
Add support for generic properties

### LINKED ISSUE #243: Possibility of specifying schema when connecting to postgres
Hey everyone,

I'm using reactive-pg-client along with vertx. At this moment I'm trying to specify some options in order to use PgPool, but I've noticed that is "missing" some kind of way of specifying pool's schema. The options that I'm using are:

```
final PgPoolOptions options = new PgPoolOptions()
        .setHost(config.getString("HOST"))
        .setPort(Integer.parseInt(config.getString("PORT")))
        .setDatabase(config.getString("NAME"))
        .setUser(config.getString("USER"))
        .setPassword(config.getString("PASS"))
        .setMaxSize(Integer.parseInt(config.getString("POOL_MAX_SIZE")));
```

I've also tried to create a PgPoolOptions object given a connection URI, but it doesn't solve this problem. What I was expecting is something like JDBC's way of specifying schema "jdbc:postgresql://localhost:5432/mydatabase?**currentSchema=myschema**".

Am I missing out something?

Thanks in advance.

### PR DESCRIPTION
**Pull request by BillyYccc**
So we can set schema at the connection start - fixes #243.

This PR also includes minor improvements of documentation and connection uri parser.

### CODE REVIEW

**Comment by huntj88** [comment]
this ALMOST does what I want. I need the ability to remove some of the default properties for connecting to DigitalOcean's PostgreSQL connection pool. Right now i'm maintaining a branch where i'm doing this.

```
public void writeStartupMessage(StartupMessage msg) {
    ensureBuffer();

    int pos = out.writerIndex();

    out.writeInt(0);
    // protocol version
    out.writeShort(3);
    out.writeShort(0);

    writeCString(out, StartupMessage.BUFF_USER);
    Util.writeCStringUTF8(out, msg.username);
    writeCString(out, StartupMessage.BUFF_DATABASE);
    Util.writeCStringUTF8(out, msg.database);
    writeCString(out, StartupMessage.BUFF_APPLICATION_NAME);
    writeCString(out, StartupMessage.BUFF_VERTX_PG_CLIENT);
    writeCString(out, StartupMessage.BUFF_CLIENT_ENCODING);
    writeCString(out, StartupMessage.BUFF_UTF8);
    writeCString(out, StartupMessage.BUFF_DATE_STYLE);
    writeCString(out, StartupMessage.BUFF_ISO);
//    writeCString(out, StartupMessage.BUFF_INTERVAL_STYLE);
//    writeCString(out, StartupMessage.BUFF_INTERVAL_STYLE_TYPE);
    writeCString(out, StartupMessage.BUFF_EXTRA_FLOAT_DIGITS);
    writeCString(out, StartupMessage.BUFF_2);

    out.writeByte(0);
    out.setInt(pos, out.writerIndex() - pos);
  }
```

**Comment by BillyYccc** [comment]
@huntj88 Can you give some reasons why you need to remove this? You can override the properties in the `PgConnectOptions` with this PR, and `postgres` is the default `IntervalStyle` stated in the [documentation](https://www.postgresql.org/docs/current/runtime-config-client.html#RUNTIME-CONFIG-CLIENT-FORMAT).

**Comment by huntj88** [comment]
Digital ocean came out with new managed PostgreSQL instances not very long ago. The client has no problem with connecting to the managed instance, but they only give you ~three connections unless you use their pool (running PgBouncer). I don't know how its configured under the hood but the pool will throw and an error if you include those.

**Comment by huntj88** [comment]
here is part of a stack trace without the modifications to the library

```
io.reactiverse.pgclient.PgException: unsupported startup parameter: intervalStyle
	at io.reactiverse.pgclient.impl.InitCommand.handleErrorResponse(InitCommand.java:95) ~[reactive-pg-client-0.11.3.jar:0.11.3]
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeError(MessageDecoder.java:253) ~[reactive-pg-client-0.11.3.jar:0.11.3]
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeMessage(MessageDecoder.java:142) ~[reactive-pg-client-0.11.3.jar:0.11.3]
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:122) ~[reactive-pg-client-0.11.3.jar:0.11.3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
```

it will only show one error at a time, and will present a different error once you comment out the intervalStyle

**Pull request closed without merging**
