### PR TITLE
add testcases for #237.

### PR DESCRIPTION
**Pull request by foxgem**
Add two test cases for #237. And I tried these two cases could pass with current code. This issue might have been fixed somewhere.

### CODE REVIEW

**Comment by vietj** [comment]
looks good but is there a point of using chars for the test which are not in the ASCII range ?

**Comment by foxgem** [comment]
Not necessarily, it is just a test data in Chinese.

**Comment by vietj** [comment]
@foxgem can you write them in plain ascii ? I don't dislike chinese, but I'm more worried about text editors opening such files and saving them incorrectly.

**Comment by foxgem** [comment]
@vietj Done, please check it, thanks.

**Pull request merged**
