### PR TITLE
Accept null value for json parameter

### PR DESCRIPTION
**Pull request by ybonnel**
A JSON column can be nullable, so a null value must be accepted

### CODE REVIEW

**Comment by vietj** [comment]
we need a test for this

**Comment by ybonnel** [comment]
I added the test for all types, so i fixed for enum too.

**Comment by ybonnel** [comment]
@vietj is the test good enough?

**Comment by vietj** [comment]
it looks great! thanks for the contribution!

**Comment by ybonnel** [comment]
@vietj just for my information, have you planned a release in days/weeks comming ?

**Comment by vietj** [comment]
I think it's can be easily done over the week end

**Comment by vietj** [comment]
the base version will be 3.6, however it will be tested for 3.6 and 3.5.4

**Comment by ybonnel** [comment]
Cool

**Pull request merged**
